<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.3.0.0</Version>
    <Author>Asvel</Author>
    <Name>Literal Map Link</Name>
    <Punchline>Turn map coordinates literal into interactable map link.</Punchline>
    <Description>
      Turn map coordinates literal into interactable map link when you post in-game chat messages.
    </Description>
    <RepoUrl>https://github.com/Asvel/ffxiv-literal-map-link</RepoUrl>
    <Tags>utility;social</Tags>

    <Nullable>disable</Nullable>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
</Project>
